[workspace]
resolver = "2"
members = [
  "signer",
  ".generated-sources/emily",
]

[profile.dev]
# Disabling debug info speeds up builds a bunch,
# and we don't rely on it for debugging that much.
debug = 0

[profile.release]
lto = "thin"
codegen-units = 16
emily = { version = "0.1.0", path = ".generated-sources/emily" }
