apiVersion: apps/v1
kind: Deployment
metadata:
  name: nakamoto-signer-2-deployment
  namespace: sbtc-signer
  labels:
    app: nakamoto-signer-2
  
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: nakamoto-signer-2
  
  template:
    metadata:
      labels:
        app: nakamoto-signer-2
    
    spec:
      
      # Define a shared volume
      volumes:
        - name: shared-data
          emptyDir: {}
        - name: chainstate
          emptyDir: {}


      # Define init containers
      initContainers:
        - name: init-file-generator
          image: debian:bookworm
          imagePullPolicy: Never
          command:
            - /bin/bash
          args: 
            - -ec
            - |
              #!/bin/bash

              SHARED_VOL_DIR="/mnt/shared"


              tee -a $SHARED_VOL_DIR/config.toml << END
              node_host = "$STACKS_NODE_RPC_HOST:$STACKS_NODE_RPC_PORT"
              endpoint = "$SIGNER_ENDPOINT"

              # Either “testnet” or “mainnet”
              network = "testnet"

              db_path = "$SIGNER_DB_PATH"

              auth_password = "$MY_HTTP_AUTH_TOKEN"

              stacks_private_key = "$STACKS_PRIVATE_KEY"
              END
          
          env:
            - name: SIGNER_ENDPOINT
              value: "0.0.0.0:30000"


            - name: MY_HTTP_AUTH_TOKEN
              value: "helloworld"

            ### (If you want to use a secret)
            # - name: MY_HTTP_AUTH_TOKEN
            #   valueFrom:
            #     secretKeyRef:
            #       name: stacks-secret
            #       key: MY_HTTP_AUTH_TOKEN
            
            - name: STACKS_PRIVATE_KEY
              value: "b463f0df6c05d2f156393eee73f8016c5372caa0e9e29a901bb7171d90dc4f1401"

            ### (If you want to use a secret)
            # - name: STACKS_PRIVATE_KEY
            #   valueFrom:
            #     secretKeyRef:
            #       name: nakamoto-signer-1-secret
            #       key: STACKS_PRIVATE_KEY


            - name: STACKS_NODE_RPC_HOST
              value: "stacks-node-service.sbtc-signer"
            - name: STACKS_NODE_RPC_PORT
              value: "20443"
            - name: SIGNER_DB_PATH
              value: "/chainstate/nakamoto-signer-2.sqlite"


          volumeMounts:
            - name: shared-data
              mountPath: /mnt/shared


      containers:
      - name: nakamoto-signer-container
        image: minikube/nakamoto-signer:v1
        imagePullPolicy: Never

        volumeMounts:
        - name: shared-data
          mountPath: /mnt/shared
        - name: chainstate
          mountPath: /chainstate
        
        resources:
          requests:
            memory: 128Mi
            cpu: 50m
          limits:
            memory: 256Mi
            cpu: 100m
        
        ports:
          - containerPort: 30000
            protocol: TCP
          - containerPort: 30000
            protocol: UDP

        env:
          - name: RUST_BACKTRACE
            value: "1"