---
apiVersion: v1
kind: Secret
metadata:
  name: bitcoin-secret
  namespace: sbtc-signer
type: Opaque
data:
  # these values are base64 encoded
  BTC_RPCUSER: ZGV2bmV0
  BTC_RPCPASSWORD: ZGV2bmV0
  MINER_ADDRESS: bWlFSnROS2EzQVNwQTE5djVaaHZiS1RFaWVZakxwekNZVA==
---
apiVersion: v1
kind: Secret
metadata:
  name: stacks-secret
  namespace: sbtc-signer
type: Opaque
data:
  # these values are base64 encoded
  LOCAL_PEER_SEED: M2ZkNjhhOGZjYWIwMDQ3NTRkNmZlZTQ3NTZkZDljODRhZDY0ZWUxOWExMWFhOTkzMDg5MzU0MGUxMzU3Njk2ZjJmNzM5NTdjZDZlOTI3OTdkN2E2NmQxZDNhZTRhNGVhNzUyYTg5MjRmZTAyOGYxZmMyYzA2YjlkNmQwZWUwYWQ=
  MY_HTTP_AUTH_TOKEN: aGVsbG93b3JsZA==
  MINER_KEY: OWU0NDZmNmIwYzZhOTZjZjIxOTBlNTRiY2Q1YTg1NjljM2UzODZmMDkxNjA1NDk5NDY0Mzg5YjhkNGUwYmZjMjAx
---
apiVersion: v1
kind: Secret
metadata:
  name: nakamoto-signer-1-secret
  namespace: sbtc-signer
type: Opaque
data:
  # these values are base64 encoded
  STACKS_PRIVATE_KEY: NmExYTc1NGJhODYzZDdiYWIxNGFkYmJjM2Y4ZWJiMDkwYWY5ZTg3MWFjZTYyMWQzZTVhYjYzNGUxNDIyODg1ZTAx
---
apiVersion: v1
kind: Secret
metadata:
  name: nakamoto-signer-2-secret
  namespace: sbtc-signer
type: Opaque
data:
  # these values are base64 encoded
  STACKS_PRIVATE_KEY: YjQ2M2YwZGY2YzA1ZDJmMTU2MzkzZWVlNzNmODAxNmM1MzcyY2FhMGU5ZTI5YTkwMWJiNzE3MWQ5MGRjNGYxNDAx
---
apiVersion: v1
kind: Secret
metadata:
  name: nakamoto-signer-3-secret
  namespace: sbtc-signer
type: Opaque
data:
  # these values are base64 encoded
  STACKS_PRIVATE_KEY: NzAzNmIyOWNiNWUyMzVlNWZkOWIwOWFlM2U4ZWVjNDQwNGU0NDkwNjgxNGQ1ZDAxY2JjYTk2OGE2MGVkNGJmYjAx
---
apiVersion: v1
kind: Secret
metadata:
  name: stacker-secret
  namespace: sbtc-signer
type: Opaque
data:
  # these values are base64 encoded
  STACKING_KEYS: NmExYTc1NGJhODYzZDdiYWIxNGFkYmJjM2Y4ZWJiMDkwYWY5ZTg3MWFjZTYyMWQzZTVhYjYzNGUxNDIyODg1ZTAxLGI0NjNmMGRmNmMwNWQyZjE1NjM5M2VlZTczZjgwMTZjNTM3MmNhYTBlOWUyOWE5MDFiYjcxNzFkOTBkYzRmMTQwMSw3MDM2YjI5Y2I1ZTIzNWU1ZmQ5YjA5YWUzZThlZWM0NDA0ZTQ0OTA2ODE0ZDVkMDFjYmNhOTY4YTYwZWQ0YmZiMDE=
---
apiVersion: v1
kind: Secret
metadata:
  name: tx-broadcaster-secret
  namespace: sbtc-signer
type: Opaque
data:
  # these values are base64 encoded
  ACCOUNT_KEYS: MGQyZjk2NWI0NzJhODJlZmQ1YTk2ZTY1MTNjOGI5ZjdlZGM3MjVkNWM5NmM3ZDM1ZDZjNzIyY2VkZWI4MGQxYjAxLDk3NWIyNTFkZDc4MDk0NjllZjBjMjZlYzM5MTc5NzFiNzVjNTFjZDczYTAyMjAyNGRmNGJmM2IyMzJjYzJkYzAwMSxjNzE3MDBiMDdkNTIwYThjOTczMWU0ZDBmMDk1YWE2ZWZiOTFlMTZlMjVmYjI3Y2UyYjcyZTdiNjk4ZjgxMjdhMDE=
---