
x-common-vars:
  - &STACKING_CYCLES ${STACKING_CYCLES:-1}
  - &STACKS_25_HEIGHT ${STACKS_25_HEIGHT:-108}
  - &STACKS_30_HEIGHT ${STACKS_30_HEIGHT:-1000001}
  - &POX_PREPARE_LENGTH ${POX_PREPARE_LENGTH:-5}
  - &POX_REWARD_LENGTH ${POX_REWARD_LENGTH:-20}
  - &EXIT_FROM_MONITOR 1 # set to "1" to automatically shut down via monitor.ts
  - &NAKAMOTO_BLOCK_INTERVAL 2
  - &BTC_ADDR miEJtNKa3ASpA19v5ZhvbKTEieYjLpzCYT


services:
  bitcoin:
    image: bitcoin:latest
    container_name: bitcoin
    stop_grace_period: 5s
    build:
      context: ./bitcoin/docker
      args:
        VERSION: "25.0"
        BTC_NETWORK: "regtest"
        BTC_PRINTTOCONSOLE: 1
        BTC_DISABLEWALLET: 0
        BTC_TXINDEX: 1
        BTC_RPCBIND: "0.0.0.0"
        BTC_RPCALLOWIP: "0.0.0.0"
        BTC_RPCPASSWORD: "devnet"
        BTC_RPCUSER: "devnet"
        BTC_RPC_PORT: 18443
        BTC_P2P_PORT: 18444
        BTC_LOG_DEBUG: 0
        BTC_REST_ENABLE: 0
    ports:
      - 18444:18444
      - 18443:18443
      - 18433:18433
    environment:
      BTC_NETWORK: regtest
      BTC_PRINTTOCONSOLE: 1
      BTC_DISABLEWALLET: 0
      BTC_TXINDEX: 1
      BTC_RPCBIND: "0.0.0.0"
      BTC_RPCALLOWIP: "0.0.0.0/0"
      BTC_RPCPASSWORD: devnet
      BTC_RPCUSER: devnet
      BTC_RPC_PORT: 18443
      BTC_P2P_PORT: 18444
      BTC_LOG_DEBUG: 0
      BTC_REST_ENABLE: 0
  postgres:
    image: postgres:15-alpine
    container_name: postgres
    stop_grace_period: 5s
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  mariadb:
    image: mariadb:10.5.21
    container_name: mariadb
    stop_grace_period: 5s
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: "mempool"
      MYSQL_USER: "mempool"
      MYSQL_PASSWORD: "mempool"
      MYSQL_ROOT_PASSWORD: "admin"
  bitcoin-miner:
    image: bitcoin-miner-sidecar:latest
    container_name: bitcoin-miner-sidecar
    stop_grace_period: 5s
    build:
      context: ./bitcoin-miner-sidecar/docker
      args:
        INIT_BTC_BLOCKS: 101
        BTC_BLOCK_GEN_TIME: 10
        BITCOIN_RPC_HOST: "bitcoin"
        BITCOIN_RPC_PORT: 18443
        BTC_RPCPASSWORD: devnet
        BTC_RPCUSER: devnet
        # MINER_ADDRESS: "moU2g2zzH3qLYCNPXGPAMqsgxr2Bw15V2j"
        MINER_ADDRESS: *BTC_ADDR
    depends_on:
      - bitcoin
  
  stacks:
    image: stacks:latest
    container_name: stacks
    stop_grace_period: 5s
    build:
      context: ./stacks/docker
      args:
        STACKS_LOG_DEBUG: 0
        STACKS_LOG_JSON: 0
    ports:
      - 20444:20444
      - 20443:20443
    depends_on:
      - bitcoin
      - bitcoin-miner
    environment:
      STACKS_LOG_DEBUG: 0
      STACKS_LOG_JSON: 0
  
  nakamoto-signer-1:
    image: nakamoto-signer-1:latest
    container_name: nakamoto-signer-1
    stop_grace_period: 5s
    build:
      context: ./nakamoto-signer/docker
      args:
        SIGNER_ENDPOINT: "0.0.0.0:30001"
        MY_HTTP_AUTH_TOKEN: "helloworld"
        STACKS_PRIVATE_KEY: "6a1a754ba863d7bab14adbbc3f8ebb090af9e871ace621d3e5ab634e1422885e01"
        STACKS_NODE_RPC_HOST: "stacks"
        STACKS_NODE_RPC_PORT: "20443"
        RUST_BACKTRACE: "1"
        SIGNER_DB_PATH: "/var/stacks/nakamoto-signer-1.sqlite"
    ports:
      - 30001:30001
    environment:
      RUST_BACKTRACE: "1"
  nakamoto-signer-2:
    image: nakamoto-signer-2:latest
    container_name: nakamoto-signer-2
    stop_grace_period: 5s
    build:
      context: ./nakamoto-signer/docker
      args:
        SIGNER_ENDPOINT: "0.0.0.0:30002"
        MY_HTTP_AUTH_TOKEN: "helloworld"
        STACKS_PRIVATE_KEY: "b463f0df6c05d2f156393eee73f8016c5372caa0e9e29a901bb7171d90dc4f1401"
        STACKS_NODE_RPC_HOST: "stacks"
        STACKS_NODE_RPC_PORT: "20443"
        RUST_BACKTRACE: "1"
        SIGNER_DB_PATH: "/var/stacks/nakamoto-signer-2.sqlite"
    ports:
      - 30002:30002
    environment:
      RUST_BACKTRACE: "1"
  nakamoto-signer-3:
    image: nakamoto-signer-3:latest
    container_name: nakamoto-signer-3
    stop_grace_period: 5s
    build:
      context: ./nakamoto-signer/docker
      args:
        SIGNER_ENDPOINT: "0.0.0.0:30003"
        MY_HTTP_AUTH_TOKEN: "helloworld"
        STACKS_PRIVATE_KEY: "7036b29cb5e235e5fd9b09ae3e8eec4404e44906814d5d01cbca968a60ed4bfb01"
        STACKS_NODE_RPC_HOST: "stacks"
        STACKS_NODE_RPC_PORT: "20443"
        RUST_BACKTRACE: "1"
        SIGNER_DB_PATH: "/var/stacks/nakamoto-signer-3.sqlite"
    ports:
      - 30003:30003
    environment:
      RUST_BACKTRACE: "1"
  
  stacks-api:
    image: stacks-api:latest
    container_name: stacks-api
    stop_grace_period: 5s
    build:
      context: ./stacks-api/docker
      args:
        GIT_URI: "https://github.com/hirosystems/stacks-blockchain-api.git"
        GIT_BRANCH: "v7.10.0-nakamoto.7"
    ports:
      - 3999:3999
      - 3700:3700
    depends_on:
      - postgres
      - stacks
      - bitcoin
    environment:
      NODE_ENV: "production"
      GIT_TAG: "v7.10.0-nakamoto.7"
      PG_HOST: "postgres"
      PG_PORT: 5432
      PG_USER: "postgres"
      PG_PASSWORD: "postgres"
      PG_DATABASE: "postgres"
      STACKS_CHAIN_ID: "0x80000000"
      STACKS_CORE_EVENT_PORT: 3700
      STACKS_CORE_EVENT_HOST: "0.0.0.0"
      STACKS_BLOCKCHAIN_API_PORT: 3999
      STACKS_BLOCKCHAIN_API_HOST: "0.0.0.0"
      STACKS_CORE_RPC_HOST: "stacks"
      STACKS_CORE_RPC_PORT: 20443
      API_DOCS_URL: http://localhost:3999/doc
  stacks-explorer:
    image: stacks-explorer
    container_name: stacks-explorer
    stop_grace_period: 5s
    build:
      context: ./stacks-explorer/docker
      args:
        GIT_URI: "https://github.com/hirosystems/explorer.git"
        GIT_BRANCH: "v1.170.1"
    ports:
      - 3020:3000
    depends_on:
      - bitcoin
      - stacks
      - stacks-api
      - postgres
    environment:
      NEXT_PUBLIC_MAINNET_API_SERVER: "http://stacks-api:3999"
  
  stacker:
    image: stacker:latest
    container_name: stacker
    stop_grace_period: 5s
    build:
      context: ./stacker/docker
      args:
        GIT_URI: 'https://github.com/hirosystems/stacks-regtest-env.git'
        GIT_BRANCH: 'feat/signer'
    depends_on:
      - stacks
    environment:
      STACKS_CORE_RPC_HOST: stacks
      STACKS_CORE_RPC_PORT: 20443
      STACKING_CYCLES: *STACKING_CYCLES
      STACKING_KEYS: 6a1a754ba863d7bab14adbbc3f8ebb090af9e871ace621d3e5ab634e1422885e01,b463f0df6c05d2f156393eee73f8016c5372caa0e9e29a901bb7171d90dc4f1401,7036b29cb5e235e5fd9b09ae3e8eec4404e44906814d5d01cbca968a60ed4bfb01
      STACKS_25_HEIGHT: *STACKS_25_HEIGHT
      STACKS_30_HEIGHT: *STACKS_30_HEIGHT
      POX_PREPARE_LENGTH: *POX_PREPARE_LENGTH
      POX_REWARD_LENGTH: *POX_REWARD_LENGTH
      STACKING_INTERVAL: 2 # interval (seconds) for checking if stacking transactions are needed
      POST_TX_WAIT: 10 # seconds to wait after a stacking transaction broadcast before continuing the loop
      SERVICE_NAME: stacker
  
  monitor:
    image: monitor:latest
    container_name: monitor
    stop_grace_period: 5s
    build:
      context: ./stacker/docker
      args:
        GIT_URI: 'https://github.com/hirosystems/stacks-regtest-env.git'
        GIT_BRANCH: 'feat/signer'
    depends_on:
      - stacks
    environment:
      STACKS_CORE_RPC_HOST: stacks-api
      STACKS_CORE_RPC_PORT: 3999
      STACKING_CYCLES: *STACKING_CYCLES
      STACKING_KEYS: 6a1a754ba863d7bab14adbbc3f8ebb090af9e871ace621d3e5ab634e1422885e01,b463f0df6c05d2f156393eee73f8016c5372caa0e9e29a901bb7171d90dc4f1401,7036b29cb5e235e5fd9b09ae3e8eec4404e44906814d5d01cbca968a60ed4bfb01
      STACKS_25_HEIGHT: *STACKS_25_HEIGHT
      STACKS_30_HEIGHT: *STACKS_30_HEIGHT
      POX_PREPARE_LENGTH: *POX_PREPARE_LENGTH
      POX_REWARD_LENGTH: *POX_REWARD_LENGTH
      EXIT_FROM_MONITOR: *EXIT_FROM_MONITOR
      STACKING_INTERVAL: 2 # interval (seconds) for checking if stacking transactions are needed
      POST_TX_WAIT: 10 # seconds to wait after a stacking transaction broadcast before continuing the loop
      SERVICE_NAME: monitor

  tx-broadcaster:
    image: tx-broadcaster:latest
    container_name: tx-broadcaster
    stop_grace_period: 5s
    build:
      context: ./stacker/docker
      args:
        GIT_URI: 'https://github.com/hirosystems/stacks-regtest-env.git'
        GIT_BRANCH: 'feat/signer'
    depends_on:
      - stacks
    environment:
      STACKS_CORE_RPC_HOST: stacks
      STACKS_CORE_RPC_PORT: 20443
      NAKAMOTO_BLOCK_INTERVAL: *NAKAMOTO_BLOCK_INTERVAL
      STACKS_30_HEIGHT: *STACKS_30_HEIGHT
      ACCOUNT_KEYS: 0d2f965b472a82efd5a96e6513c8b9f7edc725d5c96c7d35d6c722cedeb80d1b01,975b251dd7809469ef0c26ec3917971b75c51cd73a022024df4bf3b232cc2dc001,c71700b07d520a8c9731e4d0f095aa6efb91e16e25fb27ce2b72e7b698f8127a01
      STACKS_25_HEIGHT: *STACKS_25_HEIGHT
      POX_PREPARE_LENGTH: *POX_PREPARE_LENGTH
      POX_REWARD_LENGTH: *POX_REWARD_LENGTH
      STACKING_INTERVAL: 2 # interval (seconds) for checking if stacking transactions are needed
      STACKING_KEYS: 6a1a754ba863d7bab14adbbc3f8ebb090af9e871ace621d3e5ab634e1422885e01,b463f0df6c05d2f156393eee73f8016c5372caa0e9e29a901bb7171d90dc4f1401,7036b29cb5e235e5fd9b09ae3e8eec4404e44906814d5d01cbca968a60ed4bfb01
      POST_TX_WAIT: 10 # seconds to wait after a stacking transaction broadcast before continuing the loop
      STACKING_CYCLES: *STACKING_CYCLES

  
  
  electrs:
    image: electrs:latest
    container_name: electrs
    stop_grace_period: 5s
    build:
      context: ./electrs/docker
    ports:
      - 60401:60401
      - 3002:3002
    depends_on:
      - bitcoin
      - bitcoin-miner
    environment:
      RUST_BACKTRACE: 1
      BITCOIN_RPC_HOST: "bitcoin"
      BITCOIN_RPC_PORT: "18443"
  mempool-web:
    image: mempool/frontend:latest
    container_name: mempool-web
    stop_grace_period: 5s
    depends_on:
      - mempool-api
      - mariadb
      - electrs
    user: "1000:1000"
    restart: on-failure
    ports:
      - 8083:8083
    environment:
      FRONTEND_HTTP_PORT: "8083"
      BACKEND_MAINNET_HTTP_HOST: "mempool-api"
    command: "./wait-for mariadb:3306 --timeout=720 -- nginx -g 'daemon off;'"
  mempool-api:
    image: mempool/backend:latest
    container_name: mempool-api
    stop_grace_period: 5s
    depends_on:
      - electrs
      - mariadb
    user: "1000:1000"
    restart: on-failure
    ports:
      - 8999:8999
    environment:
      # Connect to electrs host
      MEMPOOL_BACKEND: "electrum"
      ELECTRUM_HOST: "electrs"
      ELECTRUM_PORT: "60401"
      ELECTRUM_TLS_ENABLED: "false"
      # Connect to bitcoin rpc
      CORE_RPC_HOST: "bitcoin"
      CORE_RPC_PORT: "18443"
      CORE_RPC_USERNAME: "devnet"
      CORE_RPC_PASSWORD: "devnet"
      DATABASE_ENABLED: "true"
      DATABASE_HOST: "mariadb"
      DATABASE_DATABASE: "mempool"
      DATABASE_USERNAME: "mempool"
      DATABASE_PASSWORD: "mempool"
      STATISTICS_ENABLED: "true"
    command: "./wait-for-it.sh mariadb:3306 --timeout=720 --strict -- ./start.sh"
